Repository prgrms-be-devcourse/springboot-url-shortener, pull requests merged in 2024-01, with the labels that each got.

#50 [4기 김혜민] URL Shortener 과제 제출합니다.
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/programmers/urlshortener/UrlShortenerApplication.java
  src/main/java/com/programmers/urlshortener/domain/BaseEntity.java
  src/main/java/com/programmers/urlshortener/domain/encoder/domain/Base62Encoder.java
  src/main/java/com/programmers/urlshortener/domain/encoder/domain/EncoderType.java
  src/main/java/com/programmers/urlshortener/domain/encoder/domain/RandomEncoder.java
  src/main/java/com/programmers/urlshortener/domain/encoder/domain/UrlEncoder.java
  src/main/java/com/programmers/urlshortener/domain/url/application/UrlService.java
  src/main/java/com/programmers/urlshortener/domain/url/application/dto/request/ShortUrlCreateRequest.java
  src/main/java/com/programmers/urlshortener/domain/url/application/dto/response/ShortUrlResponse.java
  src/main/java/com/programmers/urlshortener/domain/url/domain/Url.java
  src/main/java/com/programmers/urlshortener/domain/url/domain/UrlRepository.java
  src/main/java/com/programmers/urlshortener/domain/url/presentation/UrlApiController.java
  src/main/java/com/programmers/urlshortener/domain/url/presentation/UrlViewController.java
  src/main/java/com/programmers/urlshortener/global/config/JpaConfig.java
  src/main/java/com/programmers/urlshortener/global/error/ErrorCode.java
  src/main/java/com/programmers/urlshortener/global/error/ErrorResponse.java
  src/main/java/com/programmers/urlshortener/global/error/GlobalExceptionHandler.java
  src/main/java/com/programmers/urlshortener/global/error/exception/EntityNotFoundException.java
  src/main/java/com/programmers/urlshortener/global/error/exception/InvalidValueException.java
  src/main/resources/application.yml
  src/main/resources/static/css/url.css
  src/main/resources/templates/url/detail.html
  src/main/resources/templates/url/index.html
  src/main/resources/templates/url/information-form.html
  src/main/resources/templates/url/result.html
  src/test/java/com/programmers/urlshortener/domain/url/presentation/UrlApiControllerTest.java
Labels: Team-F, 🔥 매운맛

#59 [5기 김경훈] Shorten-URL 과제 제출합니다
  .gitignore
  build.gradle
  db/initdb.d/schema-mysql.sql
  docker-compose.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  short-url-api/build.gradle
  short-url-api/gradle/wrapper/gradle-wrapper.jar
  short-url-api/gradle/wrapper/gradle-wrapper.properties
  short-url-api/http/test.http
  short-url-api/src/main/java/com/pgms/shorturlapi/ShortUrlApiApplication.java
  short-url-api/src/main/java/com/pgms/shorturlapi/event/AsyncConfig.java
  short-url-api/src/main/java/com/pgms/shorturlapi/event/UrlWatchNumberAddEvent.java
  short-url-api/src/main/java/com/pgms/shorturlapi/event/UrlWatchNumberAddEventListener.java
  short-url-api/src/main/java/com/pgms/shorturlapi/url/UrlController.java
  short-url-api/src/main/java/com/pgms/shorturlapi/url/UrlService.java
  short-url-api/src/main/resources/application.yml
  short-url-core/short-url-core-domain/build.gradle
  short-url-core/short-url-core-domain/gradle/wrapper/gradle-wrapper.jar
  short-url-core/short-url-core-domain/gradle/wrapper/gradle-wrapper.properties
  short-url-core/short-url-core-domain/src/main/java/com/pgms/shorturlcoredomain/CoreDomainConfig.java
  short-url-core/short-url-core-domain/src/main/java/com/pgms/shorturlcoredomain/common/response/CommonResponse.java
  short-url-core/short-url-core-domain/src/main/java/com/pgms/shorturlcoredomain/exception/CustomException.java
  short-url-core/short-url-core-domain/src/main/java/com/pgms/shorturlcoredomain/exception/ExceptionResponse.java
  short-url-core/short-url-core-domain/src/main/java/com/pgms/shorturlcoredomain/exception/GlobalExceptionHandler.java
  short-url-core/short-url-core-domain/src/main/java/com/pgms/shorturlcoredomain/exception/NoUrlException.java
  short-url-core/short-url-core-domain/src/main/java/com/pgms/shorturlcoredomain/url/Url.java
  short-url-core/short-url-core-domain/src/main/java/com/pgms/shorturlcoredomain/url/UrlRepository.java
  short-url-core/short-url-core-domain/src/main/java/com/pgms/shorturlcoredomain/util/AlgorithmConverter.java
  short-url-core/short-url-core-domain/src/main/java/com/pgms/shorturlcoredomain/util/Base62Converter.java
  short-url-core/short-url-core-domain/src/main/java/com/pgms/shorturlcoredomain/util/Md5HashConverter.java
  short-url-core/short-url-core-domain/src/main/resources/application.yml
  short-url-core/short-url-core-infra/build.gradle
  short-url-core/short-url-core-infra/gradle/wrapper/gradle-wrapper.jar
  short-url-core/short-url-core-infra/gradle/wrapper/gradle-wrapper.properties
  short-url-core/short-url-core-infra/src/main/java/com/pgms/shorturlcoreinfra/config/RedisCacheConfig.java
  short-url-core/short-url-core-infra/src/main/java/com/pgms/shorturlcoreinfra/config/RedisConfig.java
  short-url-core/short-url-core-infra/src/main/resources/application-infra.yml
  short-url-core/short-url-core-infra/src/test/java/com/pgms/shorturlcoreinfra/ShortUrlCoreInfraApplicationTests.java
Labels: 🔥 매운맛, Team-BingBong

#61 [5기 박영재] Shorten-URL 과제 제출합니다.
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/example/shorturl/ShortUrlApplication.java
  src/main/java/com/example/shorturl/controller/api/ApiUrlController.java
  src/main/java/com/example/shorturl/controller/web/HomeController.java
  src/main/java/com/example/shorturl/domain/Algorithm.java
  src/main/java/com/example/shorturl/domain/Url.java
  src/main/java/com/example/shorturl/dto/request/ShortUrlCreateRequest.java
  src/main/java/com/example/shorturl/dto/response/OriginUrlResponse.java
  src/main/java/com/example/shorturl/dto/response/ShortUrlResponse.java
  src/main/java/com/example/shorturl/exception/CustomException.java
  src/main/java/com/example/shorturl/exception/ErrorCode.java
  src/main/java/com/example/shorturl/exception/ErrorResponse.java
  src/main/java/com/example/shorturl/exception/GlobalExceptionHandler.java
  src/main/java/com/example/shorturl/repository/UrlRepository.java
  src/main/java/com/example/shorturl/service/UrlService.java
  src/main/java/com/example/shorturl/util/algorithm/Base62.java
  src/main/java/com/example/shorturl/util/algorithm/Sha256.java
  src/main/java/com/example/shorturl/util/encoder/Encoder.java
  src/main/java/com/example/shorturl/util/encoder/EncoderStrategy.java
  src/main/java/com/example/shorturl/util/encoder/EncoderStrategyFactory.java
  src/main/java/com/example/shorturl/util/formatter/UrlFormatter.java
  src/main/resources/application.yml
  src/main/resources/templates/index.html
  src/test/java/com/example/shorturl/controller/api/ApiUrlControllerTest.java
  src/test/java/com/example/shorturl/service/UrlServiceTest.java
  src/test/java/com/example/shorturl/util/algorithm/Base62Test.java
Labels: 🔥 매운맛, Team-BingBong

#62 [5기 김별이] Shorten-URL 과제 제출합니다.
  .gitignore
  build.gradle
  docker-compose.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/kdt/shorturl/ShortUrlApplication.java
  src/main/java/kdt/shorturl/grobal/exception/ErrorResponse.java
  src/main/java/kdt/shorturl/grobal/exception/GlobalExceptionHandler.java
  src/main/java/kdt/shorturl/grobal/exception/ShortUrlException.java
  src/main/java/kdt/shorturl/grobal/validator/UrlValid.java
  src/main/java/kdt/shorturl/grobal/validator/UrlValidator.java
  src/main/java/kdt/shorturl/url/controller/UrlController.java
  src/main/java/kdt/shorturl/url/converter/Base62Converter.java
  src/main/java/kdt/shorturl/url/converter/Sha256Converter.java
  src/main/java/kdt/shorturl/url/converter/ShortUrlConverter.java
  src/main/java/kdt/shorturl/url/domain/Algorithm.java
  src/main/java/kdt/shorturl/url/domain/Url.java
  src/main/java/kdt/shorturl/url/dto/CreateShortUrlRequest.java
  src/main/java/kdt/shorturl/url/dto/CreateShortenUrlResponse.java
  src/main/java/kdt/shorturl/url/repository/UrlRepository.java
  src/main/java/kdt/shorturl/url/service/UrlService.java
  src/main/resources/application.yml
  src/main/resources/templates/index.html
  src/test/java/kdt/shorturl/ShortUrlApplicationTests.java
  src/test/java/kdt/shorturl/url/service/UrlServiceTest.java
  src/test/resources/application-test.yml
Labels: 🔥 매운맛, Team-BingBong

#67 [5기 조은비] Shorten-URL 과제 제출합니다.
  .gitignore
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/dev/urlshortner/UrlShortnerApplication.java
  src/main/java/com/dev/urlshortner/config/UrlProperties.java
  src/main/java/com/dev/urlshortner/controller/UrlRestController.java
  src/main/java/com/dev/urlshortner/domain/KeyEncodingGenerator.java
  src/main/java/com/dev/urlshortner/domain/Url.java
  src/main/java/com/dev/urlshortner/dto/ApiResponse.java
  src/main/java/com/dev/urlshortner/dto/UrlResponse.java
  src/main/java/com/dev/urlshortner/dto/UrlStatsResponse.java
  src/main/java/com/dev/urlshortner/exception/ErrorResponse.java
  src/main/java/com/dev/urlshortner/exception/GlobalExceptionHandler.java
  src/main/java/com/dev/urlshortner/repository/UrlRepository.java
  src/main/java/com/dev/urlshortner/service/UrlService.java
  src/main/java/com/dev/urlshortner/util/Base62RandomKeyGenerator.java
  src/main/java/com/dev/urlshortner/util/ShortKeyGenerator.java
  src/main/java/com/dev/urlshortner/view/UrlViewController.java
  src/main/resources/application.yml
  src/main/resources/schema.sql
  src/main/resources/templates/index.html
  src/test/java/com/dev/urlshortner/service/UrlServiceTest.java
  src/test/resources/application-test.yml
Labels: 🔥 매운맛, Team-BingBong

#69 [5기 이한나] Shorten-URL 과제 제출합니다.
  .gitignore
  build.gradle
  docker-compose.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  http/request.http
  settings.gradle
  src/main/java/com/programmers/urlshortener/UrlShortenerApplication.java
  src/main/java/com/programmers/urlshortener/controller/ShortUrlController.java
  src/main/java/com/programmers/urlshortener/domain/ShortUrl.java
  src/main/java/com/programmers/urlshortener/dto/request/CreateShortUrlRequest.java
  src/main/java/com/programmers/urlshortener/dto/response/ShortUrlResponse.java
  src/main/java/com/programmers/urlshortener/exception/ErrorResponse.java
  src/main/java/com/programmers/urlshortener/exception/GlobalExceptionHandler.java
  src/main/java/com/programmers/urlshortener/repository/ShortUrlRepository.java
  src/main/java/com/programmers/urlshortener/service/ShortUrlService.java
  src/main/java/com/programmers/urlshortener/util/encoder/Algorithm.java
  src/main/java/com/programmers/urlshortener/util/encoder/Base62UrlEncoder.java
  src/main/java/com/programmers/urlshortener/util/encoder/Sha256UrlEncoder.java
  src/main/java/com/programmers/urlshortener/util/encoder/UrlEncoder.java
  src/main/resources/application.yml
  src/main/resources/schema.sql
  src/test/java/com/programmers/urlshortener/UrlShortenerApplicationTests.java
Labels: 🔥 매운맛, Team-BingBong

#64 [5기 김대휘] Shorten-URL 과제 제출합니다.
  .gitignore
  build.gradle
  docker-compose.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  http/test.http
  settings.gradle
  src/main/java/org/daehwi/shorturl/ShortUrlApplication.java
  src/main/java/org/daehwi/shorturl/controller/UrlController.java
  src/main/java/org/daehwi/shorturl/controller/dto/ApiResponse.java
  src/main/java/org/daehwi/shorturl/controller/dto/EncodeType.java
  src/main/java/org/daehwi/shorturl/controller/dto/ResponseStatus.java
  src/main/java/org/daehwi/shorturl/controller/dto/ShortUrlRequest.java
  src/main/java/org/daehwi/shorturl/domain/ShortUrl.java
  src/main/java/org/daehwi/shorturl/exception/CustomException.java
  src/main/java/org/daehwi/shorturl/exception/GeneralException.java
  src/main/java/org/daehwi/shorturl/exception/GlobalExceptionHandler.java
  src/main/java/org/daehwi/shorturl/repository/UrlRepository.java
  src/main/java/org/daehwi/shorturl/service/UrlService.java
  src/main/java/org/daehwi/shorturl/util/UrlValidator.java
  src/main/java/org/daehwi/shorturl/util/encoder/Base32Encoder.java
  src/main/java/org/daehwi/shorturl/util/encoder/Base62Encoder.java
  src/main/java/org/daehwi/shorturl/util/encoder/Encoder.java
  src/main/resources/application.yml
  src/test/java/org/daehwi/shorturl/ShortUrlApplicationTests.java
Labels: 🔥 매운맛, Team-BingBong

#63 [5기 팀 마르코] Shorten-URL 과제 제출합니다.
  .gitignore
  Dockerfile
  README.md
  build.gradle
  front-end/.eslintrc.js
  front-end/.prettier.config.js
  front-end/package.json
  front-end/public/favicon.ico
  front-end/public/index.html
  front-end/public/logo192.png
  front-end/public/logo512.png
  front-end/public/manifest.json
  front-end/public/robots.txt
  front-end/src/App.css
  front-end/src/App.js
  front-end/src/index.css
  front-end/src/index.js
  front-end/src/reportWebVitals.js
  front-end/src/setupTests.js
  front-end/yarn.lock
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  schema.sql
  settings.gradle
  src/main/java/marco/urlshortener/Application.java
  src/main/java/marco/urlshortener/controller/UrlController.java
  src/main/java/marco/urlshortener/domain/Url.java
  src/main/java/marco/urlshortener/dto/UrlRequest.java
  src/main/java/marco/urlshortener/dto/UrlResponse.java
  src/main/java/marco/urlshortener/exception/ErrorResponse.java
  src/main/java/marco/urlshortener/exception/UrlControllerAdvice.java
  src/main/java/marco/urlshortener/repositoy/UrlRepository.java
  src/main/java/marco/urlshortener/service/UrlService.java
  src/main/java/marco/urlshortener/util/Base62.java
  src/main/resources/application.yml
  src/test/java/marco/urlshortener/ApplicationTests.java
  src/test/java/marco/urlshortener/domain/UrlTest.java
  src/test/java/marco/urlshortener/service/UrlServiceTest.java
  src/test/resources/application.yml
Labels: Team-Marco, 💧 순한맛
